### ISSUE TITLE
Dead link in ReadMe.MD

### ISSUE THREAD

**Issue by msftrncs** [atom/node-oniguruma#85] opened 2018-09-18 18:21 UTC
Dead Link in Read-ME
```markdown
Native Node bindings to the Oniguruma regular expressions library.

Read all about Oniguruma regular expressions [here](http://oniguruma.rubyforge.org/oniguruma/files/Syntax_txt.html).

Version 2.0 of this library added an asynchronous API, the old synchronous
methods have been renamed to have a `Sync` suffix.

```

All the information I can get seems to indicate that rubyforge.org hasn't been around since 2014.

**Comment by Arcanemagus** [comment] 2018-09-20 16:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/node-oniguruma/issues/68. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-09-20 16:48 UTC
