### ISSUE TITLE
Build error on FreeBSD 12

### ISSUE THREAD

**Issue by andersbo87** [atom/node-oniguruma#95] opened 2019-05-22 12:25 UTC
I'm installing oniguruma as a dependency of another node, which results in the following failure:
**../src/onig-scanner.cc:13:82: error: too few arguments to function call, single
      argument 'context' was not specified
  ...tpl->GetFunction());
     ~~~~~~~~~~~^**

I am using FreeBSD 12, Node 12.2.0, npm 6.9.0, gmake 4.2.1 and gcc 8.3.0

Here's the full output:
`% npm install oniguruma`

> oniguruma@7.1.0 install /home/andersbo/Downloads/vscode/vscode/node_modules/oniguruma
> node-gyp rebuild

gmake: Entering directory '/home/andersbo/Downloads/vscode/vscode/node_modules/oniguruma/build'
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  AR(target) Release/obj.target/oniguruma.a
  COPY Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
../src/onig-scanner.cc:13:82: error: too few arguments to function call, single
      argument 'context' was not specified
  ...tpl->GetFunction());
     ~~~~~~~~~~~~~~~~ ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:5947:3: note: 'GetFunction'
      declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/onig-scanner.cc:61:40: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    Nan::Utf8String utf8Value(sources->Get(i));
                                       ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3416:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:91:13: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    result->Set(Nan::New<String>("index").ToLocalChecked(), Nan::New<Num...
            ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:92:13: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    result->Set(Nan::New<String>("captureIndices").ToLocalChecked(), Cap...
            ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:108:14: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    capture->Set(Nan::New<String>("index").ToLocalChecked(), Nan::New<Nu...
             ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:109:14: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    capture->Set(Nan::New<String>("start").ToLocalChecked(), Nan::New<Nu...
             ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:110:14: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    capture->Set(Nan::New<String>("end").ToLocalChecked(), Nan::New<Numb...
             ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:111:14: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    capture->Set(Nan::New<String>("length").ToLocalChecked(), Nan::New<N...
             ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/onig-scanner.cc:112:15: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    captures->Set(index, capture);
              ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8.h:3367:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/home/andersbo/.node-gyp/12.2.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
8 warnings and 1 error generated.
gmake: *** [onig_scanner.target.mk:119: Release/obj.target/onig_scanner/src/onig-scanner.o] Error 1
gmake: Leaving directory '/home/andersbo/Downloads/vscode/vscode/node_modules/oniguruma/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System FreeBSD 12.0-RELEASE-p4
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/andersbo/Downloads/vscode/vscode/node_modules/oniguruma
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN gulp-tsb@2.0.6 requires a peer of typescript@^2.0.10 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@7.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Arcanemagus** [comment] 2019-05-22 17:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/node-oniguruma/issues/92. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-05-22 17:01 UTC

**Comment by felixhao28** [comment] 2019-05-23 03:31
@andersbo87 You can use "felixhao28/node-oniguruma" for now until this is resolved. Please be aware that https://github.com/nodejs/node/issues/27803 is also causing issue for node-oniguruma to build. Please take a look at https://github.com/nodejs/node/pull/27804/files for a fix.
